### ISSUE TITLE
The paths are not suitable.

### ISSUE THREAD

**Issue by hmtrii** [xuewenyuan/TGRNet#11]
Hi guys,
When I try to test on icdar13table, I have followed the guides in REAME.md. However, I face a problem when run the `test_icdar13table.sh` .
- In files: `text.txt, train.txt, and val.txt` in folder icdar13table, the paths to pkl files are not suitable to the construction that you guide in README, for example: `/data/xuewenyuan/data/icdar13table/gt/eu-012_3_1_0.pkl`. I think it should be './datasets/icdar13table/gt/eu-012_3_1_0.pkl'. Fortunately, this problem can be easily solve by replace method.
- The other problem appear in the following stacktrace, I beleive that the paths in pkl file are wrong.
```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    evaluator = IC15Evaluator(opt)
  File "/home/ubuntu/trihuynh/TGRNet/util/evaluator_vis.py", line 19, in __init__
    self.gt_dict, self.scale_dict, self.gt_box_sum, self.masks = self.create_gt_dict(self.data_list)
  File "/home/ubuntu/trihuynh/TGRNet/util/evaluator_vis.py", line 141, in create_gt_dict
    table_img  = Image.open(table_anno['image_path']).convert("RGB")
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/PIL/Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/xuewenyuan/data/icdar13table/image/eu-012_3_1_0.jpg'
```
These problem could be handle by refactor the structure of datasets. Besides, I suggest you change instructions in README or provide the other pkl 😃.
I didn't try on the others dataset so I don't know the status in them.

**Comment by xuewenyuan** [comment]
@hmtrii  Thank you for pointing it out. I'm too busy to update these recently. However, I think this is not a problem for most researcher and engineers.

**Comment by Tao1999111** [comment]
> Hi guys, When I try to test on icdar13table, I have followed the guides in REAME.md. However, I face a problem when run the `test_icdar13table.sh` .
> 
> * In files: `text.txt, train.txt, and val.txt` in folder icdar13table, the paths to pkl files are not suitable to the construction that you guide in README, for example: `/data/xuewenyuan/data/icdar13table/gt/eu-012_3_1_0.pkl`. I think it should be './datasets/icdar13table/gt/eu-012_3_1_0.pkl'. Fortunately, this problem can be easily solve by replace method.
> * The other problem appear in the following stacktrace, I beleive that the paths in pkl file are wrong.
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 27, in <module>
>     evaluator = IC15Evaluator(opt)
>   File "/home/ubuntu/trihuynh/TGRNet/util/evaluator_vis.py", line 19, in __init__
>     self.gt_dict, self.scale_dict, self.gt_box_sum, self.masks = self.create_gt_dict(self.data_list)
>   File "/home/ubuntu/trihuynh/TGRNet/util/evaluator_vis.py", line 141, in create_gt_dict
>     table_img  = Image.open(table_anno['image_path']).convert("RGB")
>   File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/PIL/Image.py", line 2953, in open
>     fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '/data/xuewenyuan/data/icdar13table/image/eu-012_3_1_0.jpg'
> ```
> 
> These problem could be handle by refactor the structure of datasets. Besides, I suggest you change instructions in README or provide the other pkl 😃. I didn't try on the others dataset so I don't know the status in them.

Hello, have you solved this problem yet?

**Comment by YongZ-Lee** [comment]
Hey, I realized that datasets doesn't have a folder for graph_edge, how did you fix it?
