### ISSUE TITLE
Getting 'KeyError' while loading weights

### ISSUE THREAD

**Issue by ashish-kubade** [xuewenyuan/TGRNet#20]
Hi Team, 
I was running the tests on cmdd dataset using test_cmdd.sh
I am able to create the dataset correctly. 
`dataset [TbRecCMDDDataset] was created
The number of test images = 104. Testset: ./datasets/cmdd
/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
initialize network with normal
initialize network with normal
model [TbRecModel] was created
Load SUfficx best
loading the model from ./checkpoints/cmdd_overall/best_net_Backbone.pth
`

However, when I am loading the pre-trained model weights for cell Logical prediction model, I am getting following error.

`Traceback (most recent call last):
  File "test.py", line 32, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/ashishk/research/TGRNet/models/base_model.py", line 92, in setup
    self.load_networks(load_suffix, rm_layers)
  File "/home/ashishk/research/TGRNet/models/base_model.py", line 219, in load_networks
    net.load_state_dict(state_dict,strict=False)
  File "/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1590, in load_state_dict
    load(self)
  File "/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1578, in load
    load(child, prefix + name + '.')
  File "/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1578, in load
    load(child, prefix + name + '.')
  File "/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1575, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1474, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/ashishk/.pyenv/versions/3.7.0/envs/tgr/lib/python3.7/site-packages/torch_geometric/nn/dense/linear.py", line 140, in _lazy_load_hook
    weight = state_dict[prefix + 'weight']
KeyError: 'gconv_row.lin.weight'
`

Could you please provide any suggestions here?

**Comment by ashish-kubade** [comment]
Using torch-geometric 1.6.3 solved my problem. 
Can the author update this version only and remove other combinations mentioned in readme.md?
